<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoa.Projects</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Tests" />
    <InternalsVisibleTo Include="cocoa" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Core\Cocoa.Core.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.IL\Cocoa.CodeGen.IL.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.Native\Cocoa.CodeGen.Native.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.PE\Cocoa.CodeGen.PE.csproj" />
  </ItemGroup>

</Project>
