<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoa.Projects</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Tests" />
    <InternalsVisibleTo Include="cocoa" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Core\Cocoa.Core.csproj" />
    <ProjectReference Include="..\Cocoa.Core.Managed\Cocoa.Core.Managed.csproj" />
    <ProjectReference Include="..\Cocoa.Core.Native\Cocoa.Core.Native.csproj" />
    <ProjectReference Include="..\Cocoa.Core.PEFile\Cocoa.Core.PEFile.csproj" />
  </ItemGroup>

</Project>
