using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace Cocoa.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class SyntaxNodeGetChildrenGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext initializationContext)
        {
            initializationContext.RegisterSourceOutput(
                initializationContext.CompilationProvider,
                (context, compilation) =>
                {
                    Execute(context, (CSharpCompilation)compilation);
                }
            );
        }

        private void Execute(SourceProductionContext context, CSharpCompilation compilation)
        {
            var immutableArrayType = compilation.GetTypeByMetadataName("System.Collections.Immutable.ImmutableArray`1");
            var separatedSyntaxListType = compilation.GetTypeByMetadataName("Cocoa.CodeAnalysis.Syntax.SeparatedSyntaxList`1");
            var syntaxNodeType = compilation.GetTypeByMetadataName("Cocoa.CodeAnalysis.Syntax.SyntaxNode");

            var types = GetAllTypes(compilation.Assembly);
            var syntaxNodeTypes = types.Where(t => !t.IsAbstract && IsPartial(t) && IsDerivedFrom(t, syntaxNodeType));

            using var stringWriter = new StringWriter();
            using var indentedTextWriter = new IndentedTextWriter(stringWriter, (string?)"    ");

            indentedTextWriter.WriteLine($"// <auto-generated/>");
            indentedTextWriter.WriteLine();
            indentedTextWriter.WriteLine("using System;");
            indentedTextWriter.WriteLine("using System.Collections.Generic;");
            indentedTextWriter.WriteLine("using System.Collections.Immutable;");
            indentedTextWriter.WriteLine();

            using (var nameSpaceCurly = new CurlyIndenter(indentedTextWriter, "namespace Cocoa.CodeAnalysis.Syntax"))
            {
                foreach (var type in syntaxNodeTypes)
                {
                    using var classCurly = new CurlyIndenter(indentedTextWriter, $"partial class {type.Name}");
                    using var getChildCurly = new CurlyIndenter(indentedTextWriter, "public override IEnumerable<SyntaxNode> GetChildren()");

                    foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
                    {
                        if (property.Type is INamedTypeSymbol propertyType)
                        {
                            if (IsDerivedFrom(propertyType, syntaxNodeType))
                            {
                                indentedTextWriter.WriteLine($"yield return {property.Name};");
                            }
                            else if (propertyType.TypeArguments.Length == 1 &&
                                     IsDerivedFrom(propertyType.TypeArguments[0], syntaxNodeType) &&
                                     SymbolEqualityComparer.Default.Equals(propertyType.OriginalDefinition, immutableArrayType))
                            {
                                using var forCurly = new CurlyIndenter(indentedTextWriter, $"foreach (var child in {property.Name})");

                                indentedTextWriter.WriteLine($"yield return child;");
                            }
                            else if (SymbolEqualityComparer.Default.Equals(propertyType.OriginalDefinition, separatedSyntaxListType) &&
                                     IsDerivedFrom(propertyType.TypeArguments[0], syntaxNodeType))
                            {
                                using var forCurly = new CurlyIndenter(indentedTextWriter, $"foreach (var child in {property.Name}.GetWithSeparators())");

                                indentedTextWriter.WriteLine($"yield return child;");
                            }
                        }
                    }
                }
            }

            indentedTextWriter.Flush();
            stringWriter.Flush();

            var sourceText = SourceText.From(stringWriter.ToString(), Encoding.UTF8);

            context.AddSource("Cocoa.CodeAnalysis.Syntax.SyntaxNode.GetChildren.g.cs", sourceText);
        }

        private IReadOnlyList<INamedTypeSymbol> GetAllTypes(IAssemblySymbol symbol)
        {
            var result = new List<INamedTypeSymbol>();

            GetAllTypes(result, symbol.GlobalNamespace);

            result.Sort((x, y) => x.MetadataName.CompareTo(y.MetadataName));

            return result;
        }

        private void GetAllTypes(List<INamedTypeSymbol> result, INamespaceOrTypeSymbol symbol)
        {
            if (symbol is INamedTypeSymbol type)
            {
                result.Add(type);
            }

            foreach (var child in symbol.GetMembers())
            {
                if (child is INamespaceOrTypeSymbol nsChild)
                {
                    GetAllTypes(result, nsChild);
                }
            }
        }

        private bool IsDerivedFrom(ITypeSymbol? type, INamedTypeSymbol? baseType)
        {
            if (baseType == null)
            {
                return false;
            }

            while (type != null)
            {
                if (SymbolEqualityComparer.Default.Equals(type, baseType))
                {
                    return true;
                }

                type = type.BaseType;
            }

            return false;
        }

        private bool IsPartial(INamedTypeSymbol type)
        {
            foreach (var declaration in type.DeclaringSyntaxReferences)
            {
                var syntax = declaration.GetSyntax();

                if (syntax is ClassDeclarationSyntax classDeclaration)
                {
                    foreach (var modifier in classDeclaration.Modifiers)
                    {
                        if (modifier.ValueText == "partial")
                        {
                            return true;
                        }
                    }
                }
            }

            return false;
        }
    }
}
