using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace Cocoa.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class SyntaxNodeGetChildrenGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext initializationContext)
        {
            initializationContext.RegisterSourceOutput(
                initializationContext.CompilationProvider,
                (context, compilation) =>
                {
                    Execute(context, (CSharpCompilation)compilation);
                }
            );
        }

        private void Execute(SourceProductionContext context, CSharpCompilation compilation)
        {
            var immutableArrayType = compilation.GetTypeByMetadataName("System.Collections.Immutable.ImmutableArray`1");
            var separatedSyntaxListType = compilation.GetTypeByMetadataName("Cocoa.CodeAnalysis.Syntax.SeparatedSyntaxList`1");
            var syntaxNodeType = compilation.GetTypeByMetadataName("Cocoa.CodeAnalysis.Syntax.SyntaxNode");

            if (immutableArrayType == null || separatedSyntaxListType == null || syntaxNodeType == null)
            {
                return;
            }

            var types = GetAllTypes(compilation.Assembly);
            var syntaxNodeTypes = types.Where(t => !t.IsAbstract && IsPartial(t) && IsDerivedFrom(t, syntaxNodeType));

            var indentString = "    ";
            using var stringWriter = new StringWriter();
            using var indentedTextWriter = new IndentedTextWriter(stringWriter, indentString);

            indentedTextWriter.WriteLine($"// <auto-generated/>");
            indentedTextWriter.WriteLine();
            indentedTextWriter.WriteLine("using System;");
            indentedTextWriter.WriteLine("using System.Collections.Generic;");
            indentedTextWriter.WriteLine("using System.Collections.Immutable;");
            indentedTextWriter.WriteLine();

            using (var nameSpaceCurly = new CurlyIndenter(indentedTextWriter, "namespace Cocoa.CodeAnalysis.Syntax"))
            {
                foreach (var type in syntaxNodeTypes)
                {
                    using var classCurly = new CurlyIndenter(indentedTextWriter, $"partial class {type.Name}");
                    using var getChildCurly = new CurlyIndenter(indentedTextWriter, "public override IEnumerable<SyntaxNode> GetChildren()");

                    foreach (var property in GetInheritedProperties(type, syntaxNodeType))
                    {
                        if (property.Type is INamedTypeSymbol propertyType)
                        {
                            if (IsDerivedFrom(propertyType, syntaxNodeType))
                            {
                                var canBeNull = property.NullableAnnotation == NullableAnnotation.Annotated;
                                if (canBeNull)
                                {
                                    using var ifCurly = new CurlyIndenter(indentedTextWriter, $"if ({property.Name} != null)");

                                    indentedTextWriter.WriteLine($"yield return {property.Name};");
                                }
                                else
                                {
                                    indentedTextWriter.WriteLine($"yield return {property.Name};");
                                }
                            }
                            else if (propertyType.TypeArguments.Length == 1 &&
                                     IsDerivedFrom(propertyType.TypeArguments[0], syntaxNodeType) &&
                                     SymbolEqualityComparer.Default.Equals(propertyType.OriginalDefinition, immutableArrayType))
                            {
                                using var forCurly = new CurlyIndenter(indentedTextWriter, $"foreach (var child in {property.Name})");

                                indentedTextWriter.WriteLine($"yield return child;");
                            }
                            else if (SymbolEqualityComparer.Default.Equals(propertyType.OriginalDefinition, separatedSyntaxListType) &&
                                     IsDerivedFrom(propertyType.TypeArguments[0], syntaxNodeType))
                            {
                                using var forCurly = new CurlyIndenter(indentedTextWriter, $"foreach (var child in {property.Name}.GetWithSeparators())");

                                indentedTextWriter.WriteLine($"yield return child;");
                            }
                        }
                    }
                }
            }

            indentedTextWriter.Flush();
            stringWriter.Flush();

            var sourceText = SourceText.From(stringWriter.ToString(), Encoding.UTF8);

            context.AddSource("Cocoa.CodeAnalysis.Syntax.SyntaxNode.GetChildren.g.cs", sourceText);
        }

        private IReadOnlyList<INamedTypeSymbol> GetAllTypes(IAssemblySymbol symbol)
        {
            var result = new List<INamedTypeSymbol>();

            GetAllTypes(result, symbol.GlobalNamespace);

            result.Sort((x, y) => x.MetadataName.CompareTo(y.MetadataName));

            return result;
        }

        private void GetAllTypes(List<INamedTypeSymbol> result, INamespaceOrTypeSymbol symbol)
        {
            if (symbol is INamedTypeSymbol type)
            {
                result.Add(type);
            }

            foreach (var child in symbol.GetMembers())
            {
                if (child is INamespaceOrTypeSymbol nsChild)
                {
                    GetAllTypes(result, nsChild);
                }
            }
        }

        /// <summary>收集类型自身及其基类声明的实例属性（基类在前，保持源码顺序）。</summary>
        private IReadOnlyList<IPropertySymbol> GetInheritedProperties(INamedTypeSymbol type, INamedTypeSymbol syntaxNodeType)
        {
            var levels = new List<List<IPropertySymbol>>();
            var current = type;

            while (current != null &&
                   !SymbolEqualityComparer.Default.Equals(current, syntaxNodeType) &&
                   current.SpecialType != SpecialType.System_Object)
            {
                levels.Add(current.GetMembers().OfType<IPropertySymbol>().Where(p => !p.IsStatic).ToList());

                current = current.BaseType;
            }

            levels.Reverse();

            return levels.SelectMany(l => l).ToList();
        }

        private bool IsDerivedFrom(ITypeSymbol type, INamedTypeSymbol baseType)
        {
            var current = type;

            while (current != null)
            {
                if (SymbolEqualityComparer.Default.Equals(current, baseType))
                {
                    return true;
                }

                current = current.BaseType;
            }

            return false;
        }

        private bool IsPartial(INamedTypeSymbol type)
        {
            foreach (var declaration in type.DeclaringSyntaxReferences)
            {
                var syntax = declaration.GetSyntax();

                if (syntax is ClassDeclarationSyntax classDeclaration)
                {
                    foreach (var modifier in classDeclaration.Modifiers)
                    {
                        if (modifier.ValueText == "partial")
                        {
                            return true;
                        }
                    }
                }
            }

            return false;
        }
    }
}
