<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Tests" />
    <InternalsVisibleTo Include="cocoa" />
    <InternalsVisibleTo Include="Cocoa.CodeAnalysis.CSharp" />
    <InternalsVisibleTo Include="Cocoa.CodeAnalysis.Cocoa" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.PE" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.Managed.Writer" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.Native" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.Interpreter" />
    <InternalsVisibleTo Include="Cocoa.ProjectSystem" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Targeting\Cocoa.Targeting.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.Managed.Structure\Cocoa.CodeGen.Managed.Structure.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.Managed.Reader\Cocoa.CodeGen.Managed.Reader.csproj" />
  </ItemGroup>


</Project>
