<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoa.CodeAnalysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Targeting\Cocoa.Targeting.csproj" />
    <ProjectReference Include="..\Cocoa.Metadata\Cocoa.Metadata.csproj" />
  </ItemGroup>


</Project>
