<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cocoa.CodeAnalysis.Emit.Native.PEFile</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Core" />
    <InternalsVisibleTo Include="Cocoa.Core.Managed" />
    <InternalsVisibleTo Include="Cocoa.Core.Native" />
    <InternalsVisibleTo Include="Cocoa.Builder" />
    <InternalsVisibleTo Include="cocoa" />
    <InternalsVisibleTo Include="Cocoa.Tests" />
  </ItemGroup>
</Project>
