<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Tests" />
    <InternalsVisibleTo Include="cocoa" />
    <InternalsVisibleTo Include="Cocoa.Core.CSharp" />
    <InternalsVisibleTo Include="Cocoa.Core.Cocoa" />
    <InternalsVisibleTo Include="Cocoa.Core.PEFile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Core.PEFile\Cocoa.Core.PEFile.csproj" />
  </ItemGroup>

</Project>
