<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.Tests" />
    <InternalsVisibleTo Include="cocoa" />
    <InternalsVisibleTo Include="Cocoa.Core.CSharp" />
    <InternalsVisibleTo Include="Cocoa.Core.Cocoa" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.PE" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.IL" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.Native" />
    <InternalsVisibleTo Include="Cocoa.Builder" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.CodeGen.PE\Cocoa.CodeGen.PE.csproj" />
  </ItemGroup>

</Project>
