<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoa.Cli.Repl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cocoa.CodeAnalysis\Cocoa.CodeAnalysis.csproj" />
    <ProjectReference Include="..\..\Cocoa.CodeAnalysis.Cocoa\Cocoa.CodeAnalysis.Cocoa.csproj" />
  </ItemGroup>

</Project>
