<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>coc</AssemblyName>
    <RootNamespace>Cocoa.CocCompiler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Core\Cocoa.Core.csproj" />
    <ProjectReference Include="..\Cocoa.Compiler\Cocoa.Compiler.csproj" />
  </ItemGroup>

</Project>