<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cocoa</AssemblyName>
    <RootNamespace>Cocoa.Compiler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoa.Core\Cocoa.Core.csproj" />
    <ProjectReference Include="..\Cocoa.Core.Cocoa\Cocoa.Core.Cocoa.csproj" />
    <ProjectReference Include="..\Cocoa.Core.CSharp\Cocoa.Core.CSharp.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.PE\Cocoa.CodeGen.PE.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.IL\Cocoa.CodeGen.IL.csproj" />
    <ProjectReference Include="..\Cocoa.CodeGen.Native\Cocoa.CodeGen.Native.csproj" />
    <ProjectReference Include="..\Cocoa.Builder\Cocoa.Builder.csproj" />
  </ItemGroup>

</Project>
