<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cocoa.CodeGen.PE</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cocoa.CodeAnalysis" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.IL" />
    <InternalsVisibleTo Include="Cocoa.CodeGen.Native" />
    <InternalsVisibleTo Include="Cocoa.ProjectSystem" />
    <InternalsVisibleTo Include="cocoa" />
    <InternalsVisibleTo Include="Cocoa.Tests" />
  </ItemGroup>
</Project>
