<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compiler\Cocoa.Compiler.Core\Cocoa.Compiler.Core.csproj" />
    <ProjectReference Include="..\Compiler\Cocoa.Dialects.Cocoa\Cocoa.Dialects.Cocoa.csproj" />
    <ProjectReference Include="..\Compiler\Cocoa.Dialects.CSharp\Cocoa.Dialects.CSharp.csproj" />
    <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Managed.Writer\Cocoa.CodeGen.Managed.Writer.csproj" />
    <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Managed.Structure\Cocoa.CodeGen.Managed.Structure.csproj" />
    <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Managed.Reader\Cocoa.CodeGen.Managed.Reader.csproj" />
    <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Native\Cocoa.CodeGen.Native.csproj" />
    <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Native.Lir\Cocoa.CodeGen.Native.Lir.csproj" />
    <ProjectReference Include="..\Cocoa.Targeting\Cocoa.Targeting.csproj" />
  <ProjectReference Include="..\CodeGen\Cocoa.CodeGen.Interpreter\Cocoa.CodeGen.Interpreter.csproj" />
    <ProjectReference Include="..\Cocoa.Build\Cocoa.Build.csproj" />
    <ProjectReference Include="..\Cli\Cocoa.Cli\Cocoa.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>


</Project>
